docker.docker-ubuntu-networking:
	docker build -f docker-ubuntu-networking.Dockerfile . -t laixintao/docker-ubuntu-networking:20240710
	docker push laixintao/docker-ubuntu-networking:20240710
	docker tag  laixintao/docker-ubuntu-networking:20240710 laixintao/docker-ubuntu-networking:latest
	docker push laixintao/docker-ubuntu-networking:latest
